"""phase1_schema

Revision ID: 12ead58b4c93
Revises: 
Create Date: 2026-06-01 18:13:15.242699

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ead58b4c93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('djs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=500), nullable=False),
    sa.Column('remix', sa.String(length=500), nullable=True),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('isrc', sa.String(length=12), nullable=True),
    sa.Column('spotify_uri', sa.String(length=100), nullable=True),
    sa.Column('beatport_id', sa.Integer(), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('key', sa.String(length=10), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('subgenre', sa.String(length=255), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'artist', 'remix', name='uq_track_identity')
    )
    op.create_index(op.f('ix_tracks_beatport_id'), 'tracks', ['beatport_id'], unique=False)
    op.create_index(op.f('ix_tracks_isrc'), 'tracks', ['isrc'], unique=False)
    op.create_index(op.f('ix_tracks_spotify_uri'), 'tracks', ['spotify_uri'], unique=False)
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dj_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('set_type', sa.Enum('live', 'radio', 'mixtape', 'guest_mix', name='set_type_enum'), nullable=False),
    sa.Column('is_b2b', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('venue', sa.String(length=500), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dj_id'], ['djs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('start_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', 'position', name='uq_set_position')
    )
    op.create_table('transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('track_a_id', sa.Integer(), nullable=False),
    sa.Column('track_b_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('bpm_delta', sa.Float(), nullable=True),
    sa.Column('key_relationship', sa.String(length=50), nullable=True),
    sa.Column('genre_continuity', sa.Boolean(), nullable=True),
    sa.Column('track_a_duration_seconds', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.ForeignKeyConstraint(['track_a_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['track_b_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', 'position', name='uq_transition_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transitions')
    op.drop_table('set_tracks')
    op.drop_table('sets')
    op.drop_index(op.f('ix_tracks_spotify_uri'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_isrc'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_beatport_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_table('djs')
    sa.Enum('live', 'radio', 'mixtape', 'guest_mix', name='set_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###
