"""Add danceability, acousticness, release_year, getsongbpm_artist_id to tracks

Revision ID: 4cf77fe604b3
Revises: f928c587c510
Create Date: 2026-06-09 22:48:09.152659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf77fe604b3'
down_revision: Union[str, Sequence[str], None] = 'f928c587c510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('danceability', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('acousticness', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('release_year', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('getsongbpm_artist_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'getsongbpm_artist_id')
    op.drop_column('tracks', 'release_year')
    op.drop_column('tracks', 'acousticness')
    op.drop_column('tracks', 'danceability')
    # ### end Alembic commands ###
