"""add 1001tracklists fields

Revision ID: 710c2889d0f3
Revises: 4cf77fe604b3
Create Date: 2026-06-10 21:13:52.059762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710c2889d0f3'
down_revision: Union[str, Sequence[str], None] = '4cf77fe604b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('tracklists_1001_id', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('apple_music_id', sa.String(length=100), nullable=True))
    op.add_column('tracks', sa.Column('traxsource_id', sa.String(length=100), nullable=True))
    op.add_column('tracks', sa.Column('soundcloud_url', sa.String(length=500), nullable=True))
    op.add_column('tracks', sa.Column('play_count_1001', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('first_played_1001', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tracks_apple_music_id'), 'tracks', ['apple_music_id'], unique=False)
    op.create_index(op.f('ix_tracks_tracklists_1001_id'), 'tracks', ['tracklists_1001_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_tracklists_1001_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_apple_music_id'), table_name='tracks')
    op.drop_column('tracks', 'first_played_1001')
    op.drop_column('tracks', 'play_count_1001')
    op.drop_column('tracks', 'soundcloud_url')
    op.drop_column('tracks', 'traxsource_id')
    op.drop_column('tracks', 'apple_music_id')
    op.drop_column('tracks', 'tracklists_1001_id')
    # ### end Alembic commands ###
