"""add_beatport_tracks

Revision ID: b8b80629fcb0
Revises: 12ead58b4c93
Create Date: 2026-06-01 20:10:20.068984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b80629fcb0'
down_revision: Union[str, Sequence[str], None] = '12ead58b4c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beatport_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('mix_name', sa.String(length=500), nullable=True),
    sa.Column('artist', sa.String(length=1000), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('isrc', sa.String(length=12), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=10), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=False),
    sa.Column('subgenre', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beatport_tracks_genre'), 'beatport_tracks', ['genre'], unique=False)
    op.create_index(op.f('ix_beatport_tracks_isrc'), 'beatport_tracks', ['isrc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beatport_tracks_isrc'), table_name='beatport_tracks')
    op.drop_index(op.f('ix_beatport_tracks_genre'), table_name='beatport_tracks')
    op.drop_table('beatport_tracks')
    # ### end Alembic commands ###
