"""add enrichment source tracking columns

Revision ID: f928c587c510
Revises: b8b80629fcb0
Create Date: 2026-06-04 22:07:07.171682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f928c587c510'
down_revision: Union[str, Sequence[str], None] = 'b8b80629fcb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('bpm_source', sa.String(length=20), nullable=True))
    op.add_column('tracks', sa.Column('key_source', sa.String(length=20), nullable=True))
    op.add_column('tracks', sa.Column('genre_source', sa.String(length=20), nullable=True))
    op.add_column('tracks', sa.Column('subgenre_source', sa.String(length=20), nullable=True))
    op.add_column('tracks', sa.Column('label_source', sa.String(length=20), nullable=True))
    op.add_column('tracks', sa.Column('deezer_id', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('discogs_id', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('musicbrainz_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###

    # Backfill source tracking for existing Beatport-enriched tracks
    op.execute("UPDATE tracks SET bpm_source = 'beatport' WHERE beatport_id IS NOT NULL AND bpm IS NOT NULL")
    op.execute("UPDATE tracks SET key_source = 'beatport' WHERE beatport_id IS NOT NULL AND key IS NOT NULL")
    op.execute("UPDATE tracks SET genre_source = 'beatport' WHERE beatport_id IS NOT NULL AND genre IS NOT NULL")
    op.execute("UPDATE tracks SET subgenre_source = 'beatport' WHERE beatport_id IS NOT NULL AND subgenre IS NOT NULL")
    op.execute("UPDATE tracks SET label_source = 'beatport' WHERE beatport_id IS NOT NULL AND label IS NOT NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'musicbrainz_id')
    op.drop_column('tracks', 'discogs_id')
    op.drop_column('tracks', 'deezer_id')
    op.drop_column('tracks', 'label_source')
    op.drop_column('tracks', 'subgenre_source')
    op.drop_column('tracks', 'genre_source')
    op.drop_column('tracks', 'key_source')
    op.drop_column('tracks', 'bpm_source')
    # ### end Alembic commands ###
